_BASE_: "/home/i53/student/troth/code/bt/detectron2/configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml"
        # C4 has lower accuracy, especially for small objects

OUTPUT_DIR: "/home/temp_store/troth/outputs/gripper_detection_calvin"

INPUT:
  MIN_SIZE_TRAIN: (125,250,375,500)
  MIN_SIZE_TEST: 500

DATASETS:
  TRAIN: ("gripper_detection_calvin_training", )
  TEST: ("gripper_detection_calvin_validation", )

SOLVER:
  MAX_ITER: 1200

TEST:
  AUG:
    ENABLED: False
