_BASE_: "/home/i53/student/troth/code/bt/detectron2/configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml"
        # C4 has lower accuracy, especially for small objects

OUTPUT_DIR: "/home/temp_store/troth/outputs/gripper_detection_real_world"

INPUT:
  MIN_SIZE_TRAIN: (125,250,375,500)
  MIN_SIZE_TEST: 500

DATASETS:
  # cam_1
  TRAIN: ("gripper_detection_real_world_cam_1_seq_000", "gripper_detection_real_world_cam_1_seq_049", "gripper_detection_real_world_cam_1_seq_063", "gripper_detection_real_world_cam_1_seq_096")
  # cam_2
  #TRAIN: ("gripper_detection_real_world_cam_2_seq_000", "gripper_detection_real_world_cam_2_seq_068")

SOLVER:
  MAX_ITER: 1200

TEST:
  AUG:
    ENABLED: False
